id:
  in: path
  required: true
  type: string
  description: |
    The id of the service.
host:
  in: body
  required: true
  type: string
  description: |
    The host name.
name:
  in: body
  required: true
  type: string
  description: |
    The name of the service.
server.obj:
  in: body
  required: true
  type: object
  description: |
    The server object.
